package com.github.quaoz.gui;

import com.github.quaoz.managers.UserManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import java.awt.*;
import javax.swing.*;

public class Home {

	private JPanel panel;
	private LoggedInBar loggedInBar;
	private LoggedOutBar loggedOutBar;

	public JPanel resolve() {
		boolean loggedIn = UserManager.getInstance().getUser().length() > 1;

		loggedInBar.setVisible(loggedIn);
		loggedOutBar.setVisible(!loggedIn);

		return panel;
	}

	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(
			new FormLayout(
				"center:d:grow",
				"center:max(d;4px):noGrow,top:3dlu:noGrow,center:p:noGrow,center:p:noGrow"
			)
		);
		panel.setMinimumSize(new Dimension(768, 768));
		panel.setPreferredSize(new Dimension(768, 768));
		loggedInBar = new LoggedInBar();
		CellConstraints cc = new CellConstraints();
		panel.add(loggedInBar, cc.xy(1, 4));
		loggedOutBar = new LoggedOutBar();
		panel.add(loggedOutBar, cc.xy(1, 3));
		final Spacer spacer1 = new Spacer();
		panel.add(
			spacer1,
			cc.xy(1, 1, CellConstraints.FILL, CellConstraints.DEFAULT)
		);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
		loggedInBar = new LoggedInBar();
		loggedOutBar = new LoggedOutBar();
	}
}
