package com.github.quaoz.gui;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class RecordForm {
	private JPanel panel;
	private JTextField searchField;
	private JButton advancedSearchButton;
	private JButton submitRecordButton;
	private JButton profileButton;
	private JLabel nameLabel;
	private JLabel sciNameLabel;
	private JLabel sizeLabel;
	private JLabel flightTimeLabel;
	private JLabel habitatLabel;
	private JLabel foodSourceLabel;
	private JButton recordsButton;

	public RecordForm(GUI gui) {
		recordsButton.addActionListener(e -> {
			//TODO: get records
			gui.render(GUI.Content.SEARCH_RESULTS);
		});

		submitRecordButton.addActionListener(e -> {
			gui.render(GUI.Content.SUBMIT_RECORD);
		});

		advancedSearchButton.addActionListener(e -> {
			gui.render(GUI.Content.ADVANCED_SEARCH);
		});

		profileButton.addActionListener(e -> {
			gui.render(GUI.Content.PROFILE);
		});

		searchField.addActionListener(e -> {
			//TODO: Do search
			gui.render(GUI.Content.SEARCH_RESULTS);
		});
	}

	public JPanel resolve() {
		return panel;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:18px:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
		searchField = new JTextField();
		searchField.setMinimumSize(new Dimension(200, 30));
		searchField.setPreferredSize(new Dimension(200, 30));
		searchField.setText("Search");
		CellConstraints cc = new CellConstraints();
		panel.add(searchField, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		advancedSearchButton = new JButton();
		advancedSearchButton.setText("Advanced Search");
		panel.add(advancedSearchButton, cc.xy(5, 1));
		submitRecordButton = new JButton();
		submitRecordButton.setText("Submit Record");
		panel.add(submitRecordButton, cc.xy(7, 1));
		profileButton = new JButton();
		profileButton.setText("Profile");
		panel.add(profileButton, cc.xy(9, 1));
		final Spacer spacer1 = new Spacer();
		panel.add(spacer1, cc.xy(11, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer2 = new Spacer();
		panel.add(spacer2, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		nameLabel = new JLabel();
		nameLabel.setText("Label");
		panel.add(nameLabel, cc.xy(3, 3));
		sciNameLabel = new JLabel();
		sciNameLabel.setText("Label");
		panel.add(sciNameLabel, cc.xy(3, 5));
		sizeLabel = new JLabel();
		sizeLabel.setText("Size");
		panel.add(sizeLabel, cc.xy(5, 3));
		flightTimeLabel = new JLabel();
		flightTimeLabel.setText("Flight Time");
		panel.add(flightTimeLabel, cc.xy(5, 5));
		habitatLabel = new JLabel();
		habitatLabel.setText("Habitat");
		panel.add(habitatLabel, cc.xy(5, 7));
		foodSourceLabel = new JLabel();
		foodSourceLabel.setText("Food Sources");
		panel.add(foodSourceLabel, cc.xy(5, 9));
		recordsButton = new JButton();
		recordsButton.setText("View Records");
		panel.add(recordsButton, cc.xy(3, 7));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

}
