package com.github.quaoz.gui;

import com.github.quaoz.Main;
import com.github.quaoz.managers.UserManager;
import com.github.quaoz.structures.Moth;
import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import java.awt.*;
import java.io.File;
import java.lang.reflect.Method;
import java.nio.file.Paths;
import java.text.DateFormatSymbols;
import java.util.ResourceBundle;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.*;

public class RecordForm {

	private Moth moth;
	private JPanel panel;
	private JLabel nameLabel;
	private JLabel sciNameLabel;
	private JLabel sizeLabel;
	private JLabel flightTimeLabel;
	private JLabel habitatLabel;
	private JLabel foodSourceLabel;
	private JButton recordsButton;
	private LoggedInBar loggedInBar;
	private LoggedOutBar loggedOutBar;
	private JLabel image;

	public RecordForm() {
		$$$setupUI$$$();
		recordsButton.addActionListener(e -> {
			GUI.getInstance().setRecord(moth);
			GUI.getInstance().render(GUI.Content.RECORDS);
		});
	}

	public JPanel resolve() {
		boolean loggedIn = UserManager.getInstance().getUser().length() > 1;

		loggedInBar.setVisible(loggedIn);
		loggedOutBar.setVisible(!loggedIn);

		moth = GUI.getInstance().getRecord();

		nameLabel.setText("Name: " + moth.name());
		sciNameLabel.setText("Scientific name: " + moth.sciName());

		sizeLabel.setText("Size: " + moth.sizeLower() + " to " + moth.sizeUpper());
		flightTimeLabel.setText(
			"Flies from " +
			DateFormatSymbols.getInstance().getMonths()[moth.flightStart()] +
			" to " +
			DateFormatSymbols.getInstance().getMonths()[moth.flightEnd()]
		);
		habitatLabel.setText("Habitat: " + moth.habitat());
		foodSourceLabel.setText("Food sources: " + moth.food());

		File[] mothImages = Main
			.getInstance()
			.getInstallDir()
			.resolve(Paths.get("images", moth.name()))
			.toFile()
			.listFiles();

		if (mothImages != null) {
			int index = ThreadLocalRandom.current().nextInt(mothImages.length);
			ImageIcon originalIcon = new ImageIcon(mothImages[index].getPath());
			Image originalImage = originalIcon.getImage();

			int newHeight = (int) (
				originalImage.getHeight(null) * (600.0 / originalImage.getWidth(null))
			);
			ImageIcon scaledIcon = new ImageIcon(
				originalImage.getScaledInstance(600, newHeight, Image.SCALE_SMOOTH)
			);
			image.setIcon(scaledIcon);
		}

		return panel;
	}

	// spotless:off

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new FormLayout("fill:d:grow,fill:p:grow,fill:d:grow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:p:noGrow,center:p:noGrow,center:25px:noGrow,center:p:noGrow,center:26px:noGrow,center:15px:noGrow,center:18px:noGrow,top:10dlu:noGrow,center:16px:noGrow,center:17px:noGrow,center:17px:noGrow,top:3dlu:noGrow,center:23px:noGrow,center:max(d;4px):noGrow"));
		panel.setMinimumSize(new Dimension(768, 768));
		panel.setPreferredSize(new Dimension(768, 768));
		sciNameLabel = new JLabel();
		sciNameLabel.setText("");
		CellConstraints cc = new CellConstraints();
		panel.add(sciNameLabel, cc.xy(2, 9));
		recordsButton = new JButton();
		this.$$$loadButtonText$$$(recordsButton, this.$$$getMessageFromBundle$$$("ia", "view.records"));
		panel.add(recordsButton, cc.xy(2, 16));
		final Spacer spacer1 = new Spacer();
		panel.add(spacer1, cc.xywh(3, 8, 1, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer2 = new Spacer();
		panel.add(spacer2, cc.xywh(1, 8, 1, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
		sizeLabel = new JLabel();
		sizeLabel.setText("");
		panel.add(sizeLabel, cc.xy(2, 10));
		habitatLabel = new JLabel();
		habitatLabel.setText("");
		panel.add(habitatLabel, cc.xy(2, 13));
		flightTimeLabel = new JLabel();
		flightTimeLabel.setText("");
		panel.add(flightTimeLabel, cc.xy(2, 12));
		foodSourceLabel = new JLabel();
		foodSourceLabel.setText("");
		panel.add(foodSourceLabel, cc.xy(2, 11));
		nameLabel = new JLabel();
		nameLabel.setText("");
		panel.add(nameLabel, cc.xy(2, 8));
		final Spacer spacer3 = new Spacer();
		panel.add(spacer3, cc.xy(2, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer4 = new Spacer();
		panel.add(spacer4, cc.xy(2, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
		loggedInBar = new LoggedInBar();
		panel.add(loggedInBar, cc.xyw(1, 3, 3));
		loggedOutBar = new LoggedOutBar();
		panel.add(loggedOutBar, cc.xyw(1, 4, 3));
		final Spacer spacer5 = new Spacer();
		panel.add(spacer5, cc.xy(2, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		image = new JLabel();
		image.setText("");
		panel.add(image, cc.xy(2, 6, CellConstraints.CENTER, CellConstraints.DEFAULT));
		final Spacer spacer6 = new Spacer();
		panel.add(spacer6, cc.xy(2, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
	}

	private static Method $$$cachedGetBundleMethod$$$ = null;

	private String $$$getMessageFromBundle$$$(String path, String key) {
		ResourceBundle bundle;
		try {
			Class<?> thisClass = this.getClass();
			if ($$$cachedGetBundleMethod$$$ == null) {
				Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
				$$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
			}
			bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
		} catch (Exception e) {
			bundle = ResourceBundle.getBundle(path);
		}
		return bundle.getString(key);
	}

	/**
	 * @noinspection ALL
	 */
	private void $$$loadButtonText$$$(AbstractButton component, String text) {
		StringBuffer result = new StringBuffer();
		boolean haveMnemonic = false;
		char mnemonic = '\0';
		int mnemonicIndex = -1;
		for (int i = 0; i < text.length(); i++) {
			if (text.charAt(i) == '&') {
				i++;
				if (i == text.length()) break;
				if (!haveMnemonic && text.charAt(i) != '&') {
					haveMnemonic = true;
					mnemonic = text.charAt(i);
					mnemonicIndex = result.length();
				}
			}
			result.append(text.charAt(i));
		}
		component.setText(result.toString());
		if (haveMnemonic) {
			component.setMnemonic(mnemonic);
			component.setDisplayedMnemonicIndex(mnemonicIndex);
		}
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

	private void createUIComponents() {
		loggedInBar = new LoggedInBar();
		loggedOutBar = new LoggedOutBar();
	}

	//spotless:on
}
