package com.github.quaoz.gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

public class SearchResultsForm {
	public String[] records;
	private JPanel panel;
	private JList<String> recordList;
	private JScrollPane recordScrollPane;
	private JButton backButton;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	public SearchResultsForm(GUI gui) {
		backButton.addActionListener(e ->
				gui.render(GUI.Content.PAST_CONTENT)
		);
	}

	public JPanel resolve() {
		return panel;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new FormLayout("fill:d:grow", "center:d:grow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
		recordScrollPane = new JScrollPane();
		CellConstraints cc = new CellConstraints();
		panel.add(recordScrollPane, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
		recordList = new JList();
		recordScrollPane.setViewportView(recordList);
		backButton = new JButton();
		backButton.setText("Back");
		panel.add(backButton, cc.xy(1, 3));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
		recordList.setListData(records);
	}
}
