package com.github.quaoz.gui;

import com.github.quaoz.MothManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import java.awt.*;
import java.util.concurrent.CompletableFuture;

public class SubmitRecordForm {
	private JPanel panel;
	private JTextField speciesField;
	private JTextField locationField;
	private JTextField dateField;
	private JLabel speciesLabel;
	private JLabel locationLabel;
	private JLabel dateLabel;
	private JLabel sizeLabel;
	private JLabel titleLabel;
	private JButton submitButton;
	private JButton cancelButton;
	private JSpinner sizeField;
	private JLabel speciesMatchLabel;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	public SubmitRecordForm(GUI gui) {
		submitButton.addActionListener(e -> {
			//TODO: Submit record
			gui.render(GUI.Content.PAST_CONTENT);
		});

		cancelButton.addActionListener(e -> {
			gui.render(GUI.Content.PAST_CONTENT);
		});

		speciesField.getDocument().addDocumentListener(new SimpleDocumentListener() {
			private CompletableFuture<Void> completableFuture;

			@Override
			public void update(DocumentEvent e) {
				if (completableFuture != null) {
					completableFuture.cancel(false);
				}

				completableFuture = CompletableFuture.runAsync(() -> speciesMatchLabel.setText("Closest match: " + MothManager.collectMoths(speciesField.getText().strip(), 0, 1).get(0).getName()));
			}
		});
	}

	public JPanel resolve() {
		return panel;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
		panel.setMinimumSize(new Dimension(200, 220));
		panel.setPreferredSize(new Dimension(200, 220));
		speciesField = new JTextField();
		CellConstraints cc = new CellConstraints();
		panel.add(speciesField, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
		locationField = new JTextField();
		panel.add(locationField, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
		dateField = new JTextField();
		panel.add(dateField, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer1 = new Spacer();
		panel.add(spacer1, cc.xy(5, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
		final Spacer spacer2 = new Spacer();
		panel.add(spacer2, cc.xy(5, 19, CellConstraints.DEFAULT, CellConstraints.FILL));
		final Spacer spacer3 = new Spacer();
		panel.add(spacer3, cc.xy(7, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
		final Spacer spacer4 = new Spacer();
		panel.add(spacer4, cc.xy(1, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
		speciesLabel = new JLabel();
		speciesLabel.setText("Species");
		panel.add(speciesLabel, cc.xy(3, 5));
		locationLabel = new JLabel();
		locationLabel.setText("Location");
		panel.add(locationLabel, cc.xy(3, 9));
		dateLabel = new JLabel();
		dateLabel.setText("Date");
		panel.add(dateLabel, cc.xy(3, 11));
		sizeLabel = new JLabel();
		sizeLabel.setText("Size (cm)");
		panel.add(sizeLabel, cc.xy(3, 13));
		titleLabel = new JLabel();
		titleLabel.setText("Add Record");
		panel.add(titleLabel, cc.xy(5, 3));
		submitButton = new JButton();
		submitButton.setText("Submit");
		panel.add(submitButton, cc.xy(5, 15));
		cancelButton = new JButton();
		cancelButton.setText("Cancel");
		panel.add(cancelButton, cc.xy(5, 17));
		sizeField = new JSpinner();
		panel.add(sizeField, cc.xy(5, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
		speciesMatchLabel = new JLabel();
		speciesMatchLabel.setText("");
		panel.add(speciesMatchLabel, cc.xy(5, 7));
		titleLabel.setLabelFor(speciesField);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

}
